from models.budget import BudgetBreakdown
from models.trip import TravelPlan


class BudgetEngine:
    """
    Deterministic budget calculation and validation engine.

    Calculates estimated trip expenses using the structured
    travel plan generated by the agents.
    """

    DEFAULT_FOOD_PER_PERSON_PER_DAY = 500
    DEFAULT_TRANSPORT_PER_PERSON_PER_DAY = 250

    def calculate(
        self,
        plan: TravelPlan,
        budget: float,
        travelers: int,
        days: int,
    ) -> BudgetBreakdown:

        if budget < 0:
            raise ValueError("Budget cannot be negative.")

        if travelers <= 0:
            raise ValueError("Travelers must be greater than zero.")

        if days <= 0:
            raise ValueError("Days must be greater than zero.")

        flights_cost = self._calculate_flight_cost(plan)
        hotels_cost = self._calculate_hotel_cost(plan, days)
        activities_cost = self._calculate_activity_cost(plan)

        food_cost = (
            self.DEFAULT_FOOD_PER_PERSON_PER_DAY
            * travelers
            * days
        )

        transport_cost = (
            self.DEFAULT_TRANSPORT_PER_PERSON_PER_DAY
            * travelers
            * days
        )

        total = (
            flights_cost
            + hotels_cost
            + activities_cost
            + food_cost
            + transport_cost
        )

        remaining = budget - total

        within_budget = total <= budget

        budget_used_percentage = (
            (total / budget) * 100
            if budget > 0
            else 0.0
        )

        return BudgetBreakdown(
            budget=budget,
            flights=flights_cost,
            hotels=hotels_cost,
            activities=activities_cost,
            food=food_cost,
            transport=transport_cost,
            total=total,
            remaining=remaining,
            within_budget=within_budget,
            budget_used_percentage=budget_used_percentage,
        )

    def _calculate_flight_cost(self, plan: TravelPlan) -> float:
        """
        Use the cheapest available flight option.

        The FlightRecommendation contains multiple FlightOption
        objects, so we do not assume the recommendation itself
        has a price.
        """

        if plan.flights is None:
            return 0.0

        options = getattr(plan.flights, "options", [])

        prices = [
            float(option.price)
            for option in options
            if option.price is not None
        ]

        if not prices:
            return 0.0

        return min(prices)

    def _calculate_hotel_cost(
        self,
        plan: TravelPlan,
        days: int,
    ) -> float:
        """
        Use the cheapest available hotel option.

        Hotel price is per night, therefore:

            price_per_night × number_of_nights

        A trip of N days is assumed to require N-1 nights.
        """

        if plan.hotels is None:
            return 0.0

        options = getattr(plan.hotels, "options", [])

        prices = [
            float(option.price_per_night)
            for option in options
            if option.price_per_night is not None
        ]

        if not prices:
            return 0.0

        nights = max(0, days - 1)

        return min(prices) * nights

    def _calculate_activity_cost(self, plan):
        total = 0.0

        for day in plan.itinerary:
            # Structured DayPlan
            if hasattr(day, "morning"):
                activities = (
                    day.morning
                    + day.afternoon
                    + day.evening
                )

                for activity in activities:
                    if activity.estimated_cost is not None:
                        total += float(activity.estimated_cost)

            # Legacy string-based itinerary
            else:
                continue

        return total